# Generated by Django 2.2.7 on 2021-12-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_item_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='instructions',
            field=models.CharField(default='', max_length=250),
        ),
    ]
